/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AImage: typeof import('./../src/components/AImage/index.vue')['default']
    ANavbar: typeof import('./../src/components/ANavbar/index.vue')['default']
    APopup: typeof import('./../src/components/APopup/index.vue')['default']
    ASwiperList: typeof import('./../src/components/ASwiperList/index.vue')['default']
    ATabs: typeof import('./../src/components/ATabs/index.vue')['default']
    BottomHeight: typeof import('./../src/components/BottomHeight/index.vue')['default']
    HomeTabs: typeof import('./../src/components/HomeTabs/index.vue')['default']
    JmWatermark: typeof import('./../src/components/jm-watermark/index.vue')['default']
    ListOne: typeof import('./../src/components/ListOne/index.vue')['default']
    MovableArea: typeof import('./../src/components/MovableArea/index.vue')['default']
    OrderDetail: typeof import('./../src/components/OrderDetail/index.vue')['default']
    PageScroll: typeof import('./../src/components/PageScroll/index.vue')['default']
    Poster: typeof import('./../src/components/poster/index.vue')['default']
    RealName: typeof import('./../src/components/RealName/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopArea: typeof import('./../src/components/ShopArea/index.vue')['default']
    ShopBox: typeof import('./../src/components/ShopBox/index.vue')['default']
    UploadImg: typeof import('./../src/components/UploadImg/index.vue')['default']
    UploadVideo: typeof import('./../src/components/UploadVideo/index.vue')['default']
    Verify: typeof import('./../src/components/Verify/verify.vue')['default']
    VerifySlider: typeof import('./../src/components/Verify/verifySlider/verifySlider.vue')['default']
    XListScroll: typeof import('./../src/components/XListScroll/index.vue')['default']
  }
}
